const plots = [
 "A cowboy doll is profoundly threatened and jealous when a new spaceman action figure supplants him as top toy in a boy's bedroom.",
 "Book superstore magnate Joe Fox and independent book shop owner Kathleen Kelly fall in love in the anonymity of the Internet, both blissfully unaware that he's trying to put her out of business.",
 "Boy genius Lewis gives up hope of retrieving his latest invention, which was stolen by Bowler Hat Guy, then a young time-traveler named Wilbur Robinson arrives on the scene to whisk Lewis away in his time machine. The boys spend a day in the future with Wilbur's eccentric family and uncover an amazing secret at the same time.",
 "Vincent Freeman (Ethan Hawke) has always fantasized about traveling into outer space, but is grounded by his status as a genetically inferior 'invalid'. He decides to fight his fate by purchasing the genes of Jerome Morrow (Jude Law), a 'laboratory-engineered valid'. He assumes Jerome's DNA identity and joins the Gattaca space program, where he falls in love with Irene (Uma Thurman). An investigation into the death of a Gattaca officer (Gore Vidal) complicates Vincent's plans.",
 "A fairy tale adventure about a beautiful young woman and her one true love. He must find her after a long separation and save her. They must battle the evils of the mythical kingdom of Florin to be reunited with each other. Based on the William Goldman novel 'The Princess Bride' which earned its own loyal audience.",
 "Crusading nobleman Robin of Loxley (Cary Elwes) escapes from prison in Jerusalem and returns home to find that the evil Prince John (Richard Lewis) has confiscated his family estate and is abusing the citizenry. Robin enlists his blind attendant, Blinkin (Mark Blankfield), his friend Will Scarlett O'Hara (Matthew Porretta) and Little John (Eric Allan Kramer) to help regain his home. Robin also hopes to woo the beautiful Maid Marian (Amy Yasbeck), but her chastity belt may prove a challenge.",
"The adventure continues in this 'Star Wars' sequel. Luke Skywalker (Mark Hamill), Han Solo (Harrison Ford), Princess Leia (Carrie Fisher) and Chewbacca (Peter Mayhew) face attack by the Imperial forces and its AT-AT walkers on the ice planet Hoth. While Han and Leia escape in the Millennium Falcon, Luke travels to Dagobah in search of Yoda. Only with the Jedi master's help will Luke survive when the dark side of the Force beckons him into the ultimate duel with Darth Vader (David Prowse).",
"Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence, only those who can conquer their own fear will survive.",
"In 2045 the planet is on the brink of chaos and collapse, but people find salvation in the OASIS: an expansive virtual reality universe created by eccentric James Halliday. When Halliday dies, he promises his immense fortune to the first person to discover a digital Easter egg that's hidden somewhere in the OASIS. When young Wade Watts joins the contest, he finds himself becoming an unlikely hero in a reality-bending treasure hunt through a fantastical world of mystery, discovery and danger.",
"When Frederick Wentworth -- the one who got away -- crashes back into Anne Elliot's life, she must choose between putting the past behind her or listening to her heart when it comes to second chances.",
"After a bleak childhood, Jane Eyre (Mia Wasikowska) goes out into the world to become a governess. As she lives happily in her new position at Thornfield Hall, she meets the dark, cold, and abrupt master of the house, Mr. Edward Rochester (Michael Fassbender). Jane and her employer grow close in friendship and she soon finds herself falling in love with him. Happiness seems to have found Jane at last, but could Mr. Rochester's terrible secret be about to destroy it forever?",
"Two friends, a priest and a rabbi, fall in love with the same woman they knew in their youth, but the religious position of both men denies them romance.",
"Retired friends Charlie (Walter Matthau) and Herb (Jack Lemmon) pose as dance instructors on a cruise ship in this comedy. The underhanded Charlie coaxes his recently widowed brother-in-law to join him on board without disclosing the two will need to dance. Instead Charlie promises there will be plenty of available and lonely women at sea. Once on the ship, Charlie's promise proves accurate, and he starts romancing the wealthy Liz (Dyan Cannon), while Herb falls for Vivian (Gloria DeHaven).",
"Just after a bad breakup, Charlie MacKenzie (Mike Myers) falls for lovely butcher Harriet Michaels (Nancy Travis) and introduces her to his parents. But, as voracious consumers of sensational tabloids, his parents soon come to suspect that Harriet is actually a notorious serial killer -- 'Mrs. X' -- wanted in connection with a string of bizarre honeymoon killings. Thinking his parents foolish, Charlie proposes to Harriet. But while on his honeymoon with her, he begins to fear they were right.",
"With the occasion all but overshadowed by her sister's upcoming wedding, angst-ridden Samantha (Molly Ringwald) faces her 16th birthday with typical adolescent dread. Samantha pines for studly older boy Jake (Michael Schoeffling), but worries that her chastity will be a turnoff for the popular senior. Meanwhile, Samantha must constantly rebuff the affections of nerdy Ted (Anthony Michael Hall), the only boy in the school, unfortunately, who seems to take an interest in her.",
"Lane Meyer (John Cusack) is a teen with a peculiar family and a bizarre fixation with his girlfriend, Beth (Amanda Wyss). When Beth dumps Lane, he decides to kill himself, making bumbling attempts at suicide. Outside of his morbid endeavors, Lane spends time with his oddball buddy, Charles (Curtis Armstrong), and befriends Monique (Diane Franklin), a visiting French student. Eventually, Lane resolves to race Beth's obnoxious new beau on the ski slopes, with unexpected results.",
"New York City roommates Peter (Tom Selleck), Michael (Steve Guttenberg) and Jack (Ted Danson) are all successful and happily unmarried, but Peter and Michael get the surprise of a lifetime when a young woman abandons an infant in front of their loft. They also receive a letter stating that the child, named Mary, belongs to Jack, but he's away on business. Michael and Peter are then forced to care for Mary -- and though they make hopeless babysitters, they soon become quite attached to the girl.",
"Urban horticulturalist Brontë Mitchell (Andie MacDowell) has her eye on a gorgeous apartment, but the building's board will rent it only to a married couple. Georges Fauré (Gérard Depardieu), a waiter from France whose visa is expiring, needs to marry an American woman to stay in the country. Their marriage of convenience turns into a burden when they must live together to allay the suspicions of the immigration service, as the polar opposites grate on each other's nerves.",



]

export default plots